name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18.x', '1.19.x', '1.20.x' ]
        os: [ubuntu-latest]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
        cache: true

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        go mod download

    - name: Run make build
      run: make build

    - name: Run make test
      run: make test