on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        go-version: [ '1.19.x', '1.20.x' ]
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        cache: false
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        go mod download

    - name: Run make build
      run: make build

    - name: Run make test
      run: make test